<p>
  <b>BARTOC Skosmos</b> is a terminology service for all kinds of vocabularies. It complements
  the terminology registry <a href="https://bartoc.org/">BARTOC.org</a> and other
  <a href="https://bartoc.org/registries/">other terminology registries, repositories, and services</a>.
</p>
<h3>History</h3>
<p>
  BARTOC Skosmos was first developed 2018 by Jonas Waeber and Andreas Ledl at University Library Basel.
  See <a href="https://doi.org/10.1007/978-3-030-14401-2_1">their publication</a> for a detailled
  explanation of the infrastructure back then. The core of the service is 
  <a href="https://skosmos.org">Skosmos</a>, a SKOS browser and publishing tool developed at the
  Finnish National Library in 2014.
</p>
<p>
  In February 2023 the service is being transferred to the Head Office of the GBV Common Library Network
  (<a href="https://www.gbv.de/">GBV</a>) who already took over BARTOC.org in November 2020. Please
  expect some instability during the transition!
</p>
