<footer>
 <div class="container">
    <div class="row">
      <div class="col-md-10 text-muted">
        BARTOC Skosmos is currently being rebuild at
	<a href="https://www.gbv.de/">VZG</a>.
      </div>
    <div class="row">
    <div class="col-md-10 text-muted">
      <ul class="list-inline">
        <li class="list-inline-item">
	  <a href="https://www.gbv.de/impressum">Impressum</a>
	</li>
        <li class="list-inline-item">
	  <a href="https://coli-conc.gbv.de/de/erklaerung-zur-barrierefreiheit/">Barrierefreiheit</a>
	</li>
        <li class="list-inline-item">
	  <a href="https://www.gbv.de/datenschutz">Datenschutz</a>
	</li>
	<li class="list-inline-item">
	  <a rel="me" href="https://code4lib.social/@bartoc">Mastodon</a>
	</li>
	<li class="list-inline-item">
	  <a href="https://github.com/gbv/bartoc-skosmos">sources (user interface)</a>
	</li>
	<li class="list-inline-item">
	  <a href="https://github.com/gbv/bartoc.org/issues">issues</a>
	</li>
      </ul>
    </div>
  </div>
</footer>
